"GET /static/css/uploadExcel.css HTTP/1.1" 404 1816
"GET /static/css/uploadExcel.css HTTP/1.1" 404 1816
"GET /static/css/uploadExcel.css HTTP/1.1" 404 1816
"GET /static/css/uploadExcel.css HTTP/1.1" 404 1816
"GET /static/css/uploadExcel.css HTTP/1.1" 404 1816
Internal Server Error: /Applogin
Traceback (most recent call last):
  File "c:\Users\techn\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\techn\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
    ^^^^
  File "c:\Users\techn\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_trace_dispatch_regular.py", line 203, in trace_dispatch
    py_db.enable_tracing(thread_trace_func)
  File "c:\Users\techn\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\pydevd.py", line 1107, in enable_tracing
    pydevd_tracing.SetTrace(thread_trace_func)
  File "c:\Users\techn\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\pydevd_tracing.py", line 87, in SetTrace
    if set_trace_to_threads(tracing_func, thread_idents=[thread.get_ident()], create_dummy_thread=False) == 0:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\techn\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\pydevd_tracing.py", line 354, in set_trace_to_threads
    start_new_thread(increase_tracing_count, ())
RuntimeError: can't create new thread at interpreter shutdown
"POST /Applogin HTTP/1.1" 500 95519
Bad Request: /Applogin
"POST /Applogin HTTP/1.1" 400 181
Bad Request: /Applogin
"POST /Applogin HTTP/1.1" 400 181
